In [1]:
import numpy as np

In [2]:
state, action, reward, episode = np.array([1,2]), np.array([1,2]), 10, 1

In [3]:
experiences = []

In [7]:
experiences.append((state, action, reward, episode))

In [8]:
state, action, reward, episode = np.array([1,2]), np.array([1,2]), 10, 2

In [10]:
experiences.append((state, action, reward, episode))

In [11]:
experiences

[(array([1, 2]), array([1, 2]), 10, 1),
 (array([1, 2]), array([1, 2]), 10, 1),
 (array([1, 2]), array([1, 2]), 10, 2),
 (array([1, 2]), array([1, 2]), 10, 2)]

In [12]:
exp = np.asarray(experiences)

In [14]:
exp.shape

(4, 4)

In [15]:
exp

array([[array([1, 2]), array([1, 2]), 10, 1],
       [array([1, 2]), array([1, 2]), 10, 1],
       [array([1, 2]), array([1, 2]), 10, 2],
       [array([1, 2]), array([1, 2]), 10, 2]], dtype=object)

In [17]:
exp[0][3]

1

In [20]:
episode_number = 2
exps = np.asarray(experiences)                                       
episode_mask = [exps[:, 3] == episode_number]                           
episode_exps = exps[episode_mask]   
episode_exps

array([[array([1, 2]), array([1, 2]), 10, 2],
       [array([1, 2]), array([1, 2]), 10, 2]], dtype=object)

In [23]:
obs = episode_exps[:,0]
obs

array([array([1, 2]), array([1, 2])], dtype=object)

In [24]:
obs.shape


(2,)

In [27]:
obs = obs.reshape(-1,2)

In [28]:
obs.shape

(1, 2)