In [1]:
import numpy as np

from energy_py import DiscreteSpace, ContinuousSpace, GlobalSpace
from energy_py.agents import Memory

observation_space = GlobalSpace([DiscreteSpace(0,1), ContinuousSpace(0,10), ContinuousSpace(0,10)])
action_space = GlobalSpace([ContinuousSpace(50,100)])
discount = 0.9

mem = Memory(observation_space,
             action_space,
             discount,
             memory_length=10)

Using TensorFlow backend.


In [2]:
for step in range(10):
    obs = observation_space.sample()
    action = action_space.sample()
    reward = 1
    next_obs = observation_space.sample()
    terminal=np.random.choice([True,False]),
    step=step,
    episode=1
    mem.add_experience(obs, action, reward, next_obs, terminal, step, episode)


In [3]:
memory = np.array(mem.experiences)
memory.shape

(10, 7)

In [4]:
batch_size = 10
indicies = np.random.randint(low=0, high=memory.shape[0], size=batch_size).reshape(1, -1)
indicies

array([[3, 4, 2, 3, 2, 8, 9, 0, 8, 1]])

In [5]:
exp_batch = memory[indicies].reshape(batch_size, -1)

In [6]:
type(exp_batch)

numpy.ndarray

In [7]:
exp_batch.shape

(10, 7)

In [8]:
exp_batch[:,2]

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=object)

In [9]:
rews = exp_batch[:,2]
rews.shape

(10,)

In [10]:
next_obs = np.concatenate(exp_batch[:,3])
next_obs.shape

(10, 3)

In [11]:
terminal = np.concatenate(exp_batch[:,4])
terminal

array([False, False, False, False, False, False,  True, False, False, False], dtype=bool)

In [12]:
from energy_py import Standardizer

In [13]:
obs = np.concatenate(exp_batch[:,0])
obs .shape

(10, 3)

In [14]:
std = Standardizer(length=obs.shape[1])

In [15]:
scaled = std.transform(obs)
scaled.shape

(10, 3)

In [16]:
max_q = np.ones(rews.shape)
max_q.shape

(10,)

In [17]:
target = rews + max_q
target

array([2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0], dtype=object)

In [18]:
max_q[terminal] = 0

In [19]:
max_q

array([ 1.,  1.,  1.,  1.,  1.,  1.,  0.,  1.,  1.,  1.])