In [1]:
import numpy as np

from energy_py import DiscreteSpace, ContinuousSpace, GlobalSpace

In [2]:
disc = DiscreteSpace(10)

In [3]:
disc.discretize()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
disc.contains(10)

array([False], dtype=bool)

In [5]:
disc.contains(5)

array([ True], dtype=bool)

Now we try the continous spaces

In [6]:
cont = ContinuousSpace(50, 100)

In [7]:
cont.discretize(7)

array([  50.        ,   58.33333333,   66.66666667,   75.        ,
         83.33333333,   91.66666667,  100.        ])

In [8]:
cont.sample()

55.2711628680524

In [9]:
cont.contains(49)

False

In [10]:
cont.contains(55)

True

Now the global space

In [11]:
glbl = GlobalSpace([disc, cont])

In [12]:
glbl.shape

(2,)

In [13]:
#  issue here is that we arent sampling from the discrete version of the continuous action space
glbl.sample()

array([[  8.        ,  67.21100397]])

In [14]:
all_options = glbl.discretize(5)
all_options.shape

(50, 2)

In [15]:
all_options[25]

array([  5.,  50.])

In [16]:
d_sample = glbl.sample_discrete()
d_sample

array([[  6. ,  87.5]])

In [17]:
c_sample = glbl.sample()

In [18]:
#  both of these should work in the contains call
glbl.contains(d_sample)

True

In [22]:
glbl.contains(c_sample)

True

In [27]:
error = np.array([[1.5, 75]])
glbl.contains(error)

False

In [28]:
not_error = np.array([[4, 75]])
glbl.contains(not_error)

True

In [29]:
error = np.array([[8, -10]])
glbl.contains(error)

False

In [30]:
not_error = np.array([[8, 100]])
glbl.contains(not_error)

True