Bit of playing around with the space objects - mainly the action space creation

In [12]:
import numpy as np

from energy_py import DiscreteSpace, ContinuousSpace

In [13]:
c_space = ContinuousSpace(0, 100)

In [14]:
disc_act_spcs = c_space.discretize(11)
disc_act_spcs

array([   0.,   10.,   20.,   30.,   40.,   50.,   60.,   70.,   80.,
         90.,  100.])

In [17]:
disc_act_spcs = disc_act_spcs.tolist()

In [18]:
import itertools

In [25]:
actions = [a for a in itertools.product(disc_act_spcs)]

In [26]:
actions

[(0.0,),
 (10.0,),
 (20.0,),
 (30.0,),
 (40.0,),
 (50.0,),
 (60.0,),
 (70.0,),
 (80.0,),
 (90.0,),
 (100.0,)]

In [27]:
from energy_py import GlobalSpace

In [28]:
gbl = GlobalSpace([c_space, c_space])

In [31]:
gblspcs = gbl.discretize(10)
gblspcs

[array([   0.        ,   11.11111111,   22.22222222,   33.33333333,
          44.44444444,   55.55555556,   66.66666667,   77.77777778,
          88.88888889,  100.        ]),
 array([   0.        ,   11.11111111,   22.22222222,   33.33333333,
          44.44444444,   55.55555556,   66.66666667,   77.77777778,
          88.88888889,  100.        ])]

In [34]:
actions = [a for a in itertools.product(*gblspcs)]
actions

[(0.0, 0.0),
 (0.0, 11.111111111111111),
 (0.0, 22.222222222222221),
 (0.0, 33.333333333333329),
 (0.0, 44.444444444444443),
 (0.0, 55.555555555555557),
 (0.0, 66.666666666666657),
 (0.0, 77.777777777777771),
 (0.0, 88.888888888888886),
 (0.0, 100.0),
 (11.111111111111111, 0.0),
 (11.111111111111111, 11.111111111111111),
 (11.111111111111111, 22.222222222222221),
 (11.111111111111111, 33.333333333333329),
 (11.111111111111111, 44.444444444444443),
 (11.111111111111111, 55.555555555555557),
 (11.111111111111111, 66.666666666666657),
 (11.111111111111111, 77.777777777777771),
 (11.111111111111111, 88.888888888888886),
 (11.111111111111111, 100.0),
 (22.222222222222221, 0.0),
 (22.222222222222221, 11.111111111111111),
 (22.222222222222221, 22.222222222222221),
 (22.222222222222221, 33.333333333333329),
 (22.222222222222221, 44.444444444444443),
 (22.222222222222221, 55.555555555555557),
 (22.222222222222221, 66.666666666666657),
 (22.222222222222221, 77.777777777777771),
 (22.222222222222

In [35]:
d_space = DiscreteSpace(0,1)
gbl = GlobalSpace([d_space])

In [38]:
gbl.spaces

In [42]:
from energy_py.agents import BaseAgent
from energy_py.envs import BatteryEnv

AssertionError: 

In [47]:
#  get the discrete action space for all action dimensions              
#  list is used to we can use itertools.product below   
spc_len=20
disc_act_spcs = gbl.discretize(spc_len)                   
159                                                                                 
#  create every possible combination of actions                         
#  this creates the unscaled actions                                    
actions = np.array([a for a in itertools.product(*disc_act_spcs)])

In [50]:
actions.shape

(2, 1)

In [51]:
gbl.length

1

In [52]:
for i,act in actions[0]:
    assert act <= 1

TypeError: 'numpy.int64' object is not iterable

In [54]:
actions[0][:]

array([0])