In [1]:
import numpy as np
import tensorflow as tf

In [2]:
sess = tf.Session()

In [3]:
output_layer = tf.constant([1,2], dtype=tf.float32)

In [4]:
sess.run(output_layer)

array([ 1.,  2.], dtype=float32)

In [5]:
means = output_layer[:1]
stds = output_layer[1:]

In [6]:
sess.run(means)

array([ 1.], dtype=float32)

In [7]:
sess.run(stds)

array([ 2.], dtype=float32)

Now we try to parameterize a normal distribution 

In [8]:
norm_dist = tf.contrib.distributions.Normal(loc=means, scale=stds)

In [9]:
action = norm_dist.sample(2)

In [10]:
acts = []
for i in range(10000):
    acts.append(sess.run(action))
np.mean(acts, axis=0)

array([[ 1.01290011],
       [ 0.97280085]], dtype=float32)

In [11]:
np.std(acts, axis=0)

array([[ 2.00242305],
       [ 1.99308634]], dtype=float32)

In [12]:
sess.run(action)

array([[ 1.11788094],
       [ 2.20524979]], dtype=float32)

In [13]:
log_prob = norm_dist.log_prob(action)
sess.run(log_prob)

array([[-1.65504491],
       [-2.37570572]], dtype=float32)

In [14]:
rtns = np.array([2]).reshape(1,1)
loss = -log_prob * rtns

In [20]:
loss = tf.reduce_mean(log_prob * rtns)

In [21]:
sess.run(loss)

-3.8862228

In [17]:
import math
math.exp(1)

2.718281828459045

In [18]:
a = tf.exp(action)

In [19]:
sess.run(a)

array([[ 0.72475201],
       [ 9.26203728]], dtype=float32)